package fr.lo02.jest.enums;

public enum PartieState {
	
	START, LOAD, C_VARIANTE, C_BOTS, C_PLAYERS, NEW_ROUND, SAVE, NEW_SAVE, FAIRE_OFFRE, CHOISIR_OFFRE, CHOISIR_OFFRE_BOT, TROPHEES, SCOREBOARD

}
